apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: timeline-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: timeline-service
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
