apiVersion: v1
kind: Service
metadata:
  name: timeline-service
  namespace: apps
spec:
  ports:
    - name: web
      port: 80
      targetPort: 8080
  selector:
    app: timeline-service
  sessionAffinity: None
